apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
  namespace: minio
spec:
  secretName: server-cert
  issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
  dnsNames:
      - "minio.dfranklin.dev"
