apiVersion: v1
kind: PersistentVolume
metadata:
  name: data0
  namespace: minio
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
      - ReadWriteOncePod
  claimRef:
    namespace: minio
    name: data0
  hostPath:
    path: /minio-data0
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data0
  namespace: minio
spec:
  storageClassName: ""
  volumeName: data0
  accessModes:
      - ReadWriteOncePod
  resources:
    requests:
      storage: 50Gi
